version: '3'

services:
  backend:
    image: tapestry
    working_dir: /app/backend
    command: uvicorn app.main:app --reload --host 0.0.0.0 
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend

  frontend:
    image: tapestry
    working_dir: /app/frontend
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tapestry
      - POSTGRES_USER=tapestry_user
      - POSTGRES_PASSWORD=tapestry_password
    volumes:
      - main:/var/lib/postgresql/data

volumes:
  main:
